runner: make download-corpus work
Fixes
```
python3 ../runner.py download-corpus avahi
Traceback (most recent call last):
  File "/home/vagrant/fuzz-introspector/oss_fuzz_integration/oss-fuzz/../runner.py", line 652, in <module>
    download_full_public_corpus(args.project)
TypeError: download_full_public_corpus() missing 1 required positional argument: 'target_corpus_dir'
```

It also makes it possible to download corpora to specific directories by
passing --corpus-dir=...

Signed-off-by: Evgeny Vereshchagin <evvers@ya.ru>