analyser: introduce an option to control parallel mode
Fuzz Introspector is failed when building reports for Tarantool
and other projects, see [1]:

During handling of the above exception, another exception occurred:

  File "/usr/local/lib/python3.10/multiprocessing/managers.py", line 817, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/fuzz-introspector/src/fuzz_introspector/datatypes/fuzzer_profile.py", line 359, in accummulate_profile
    return_dict[uniq_id] = self
AttributeError: 'ForkAwareLocal' object has no attribute 'connection'

The issue (theoretically) is related to processing data in
parallel mode and cannot be reproduced locally. The patch
introduce an option for controlling parallel mode -
FUZZ_INTROSPECTOR_PARALLEL. When envronment variable is set to
`false` Fuzz Introspector will process data in sequential mode.

1. https://github.com/google/oss-fuzz/issues/13226

Related to #2267
Related to google/oss-fuzz#13226

Signed-off-by: Sergey Bronnikov <estetus@gmail.com>